### ISSUE TITLE
The installation command from README doesn't work.

### ISSUE THREAD

**Issue by curioswati** [datagovuk/ckanext-issues#23]
The installation command failed with

    ERROR: Could not detect requirement name for 'git+http://github.com/ckan/ckanext-issues', please specify one with #egg=your_package_name

System details:

    OS: ubuntu 18.04
    Python: 2.7.15rc1

It possibly should be:

    pip install -e git+https://github.com/ckan/ckanext-issues.git#egg=ckanext-issues

**Comment by rossjones** [comment]
You probably want to report this at https://github.com/ckan/ckanext-issues - this is the old home for it and is pretty much unused.

**Comment by curioswati** [comment]
Thanks @rossjones I'll report there.
