### ISSUE TITLE
Delete issue page layout is messed up

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-issues#3]
![delete-issue](https://cloud.githubusercontent.com/assets/3272/11077283/27be79c6-87f7-11e5-817c-d674ce26ea20.png)

**Comment by davidread** [comment]
Good to find this - yes we've styled several of the pages, but this needs doing. Can you do this?

What we've been doing is adding DGU-specific CSS to dgu-ckan.less. We've been copying the relevant bits from ckanext-issues and tweaking it to work for DGU. For example:

https://github.com/datagovuk/ckanext-dgu/compare/1829-issues#diff-b2ce91f534e2c92c7d30207e5d85b1e3R1789
